---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-game-server-deployment
  labels:
    app: game-server
spec:
  replicas: {{ int .Values.gameServer.replicas }}
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
      - name: api
        image: {{ .Values.gameServer.image }}
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "3030"
        ports:
          - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-game-server-service
spec:
  selector:
    app: game-server
  ports:
  - port: 80
    targetPort: 3030
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    app: game-server
  name: {{ .Release.Name }}-game-server-ingress
spec:
  tls:
  - hosts:
    - {{ .Values.gameServer.externalHostname }}
    secretName: {{ .Values.gameServer.tlsSecret }}
  rules:
  - host: "{{ .Values.gameServer.externalHostname }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-game-server-service
          servicePort: 80
