---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user-app-deployment
  labels:
    app: user-app
spec:
  replicas: {{ int .Values.userApp.replicas }}
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: api
        image: {{ .Values.userApp.image }}
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: production
        - name: METEOR_ALLOW_SUPERUSER
          value: "true"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-user-app-service
spec:
  selector:
    app: user-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    app: user-app
  name: {{ .Release.Name }}-user-app-ingress
spec:
  tls:
  - hosts:
    - {{ .Values.userApp.externalHostname }}
    secretName: {{ .Values.userApp.tlsSecret }}
  rules:
  - host: "{{ .Values.userApp.externalHostname }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-user-app-service
          servicePort: 80
